version: '3.3'

networks:
  prod:
    driver: bridge

services: 
  botwatch: 
    image: timdeka/botwat.ch:beta
    container_name: botwatch
    restart: always
    depends_on:
      - db
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    networks:
      - prod
      
  db:
    image: postgres:12
    container_name: db
    restart: "no"
    ports:
      - "5432"
    environment:
      POSTGRES_USER: botwatch
      POSTGRES_PASSWORD: FireSnail678!
    networks: 
      - prod
      
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    networks: 
      - prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: watchtower botwatch --interval 30
    restart: always
