version: '3.3'
services: 
  db:
    image: postgres:11
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: botwatch
      POSTGRES_PASSWORD: FireSnail678!
  botwatch: 
    image: "timdeka/botwat.ch"
    container_name: botwatch
    restart: always
    ports:
     - 0.0.0.0:80:80
     - 0.0.0.0:443:443
