version: '3.3'

networks:
  prod:
    driver: bridge

services: 
  botwatch: 
    image: timdeka/botwat.ch:latest
    container_name: botwatch
    restart: always
    depends_on:
      - db
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    networks:
      - prod
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: botwatch
      POSTGRES_PASSWORD: FireSnail678!
    networks: 
      - prod
