version: '3.3'
services:
  botwatch: 
    image: "timdeka/botwat.ch"
    restart: always
  db:
    image: postgres:11
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: botwatch
      POSTGRES_PASSWORD: FireSnail678!
      
     
