version: '3.3'
services: 
  db:
    image: postgres:11
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: botwatch
      POSTGRES_PASSWORD: FireSnail678!
  botwatch: 
    image: "timdeka/botwat.ch"
    restart: always
    ports:
     - "443:443"
